"""Write supabase/seed.sql: gazetteer (with PSGC), boundaries (version 1) and legend presets.

Run after build_reference:  python -m scripts.build_seed_sql
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from shapely.geometry import mapping

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from agriclimate import classes, reference  # noqa: E402

OUT = ROOT.parent / "supabase" / "seed.sql"


def q(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    return "'" + str(v).replace("'", "''") + "'"


def main():
    g = reference.gazetteer_table()
    muni, prov = reference.boundaries()
    lines = ["-- Generated by worker/scripts/build_seed_sql.py – do not edit by hand.", "begin;", ""]
    lines.append("insert into gazetteer (area_key, psgc, province, municipality, gis_name, short_name, is_city, aliases) values")
    rows = []
    for _, r in g.iterrows():
        aliases = "{" + ",".join(f'"{a}"' for a in ({"BENGUET|BAGUIO": ["City of Baguio", "Baguio"],
                                                       "KALINGA|TABUK": ["City of Tabuk", "Tabuk"]}.get(r.area_key, []))) + "}"
        rows.append(f"  ({q(r.area_key)}, {q(r.psgc)}, {q(r.province_label)}, {q(r.label)}, {q(r.gis_name)}, "
                    f"{q(r.short_name)}, {q(bool(r.is_city))}, {q(aliases)})")
    lines.append(",\n".join(rows) + "\non conflict (area_key) do update set psgc = excluded.psgc, gis_name = excluded.gis_name;")
    lines += ["", "insert into boundary_versions (id, label, source, is_current) values "
              "(1, 'CAR Regional Map (municipal/provincial shapefiles, EPSG:4326)', 'DA-RFO-CAR', true) "
              "on conflict (id) do nothing;", ""]
    for level, df, name_col in (("municipality", muni, "Mun_Name"), ("province", prov, "Pro_Name")):
        for _, r in df.iterrows():
            gj = json.dumps(mapping(r.geometry), separators=(",", ":"))
            lines.append(f"insert into boundaries (version_id, level, area_key, name, geom) values (1, '{level}', "
                         f"{q(r.area_key)}, {q(r[name_col])}, st_multi(st_setsrid(st_geomfromgeojson({q(gj)}), 4326))) "
                         "on conflict do nothing;")
    lines.append("")
    ptype = {"rainfall_dekad": "rainfall_dekad", "rainfall_month": "rainfall_seasonal", "rainfall_season": "rainfall_seasonal",
             "pct_normal": "rainfall_seasonal", "drought": "drought", "envi": "envi"}
    for lid, lg in classes.PRESETS.items():
        lines.append(f"insert into legends (id, product_type, definition) values ({q(lid)}, {q(ptype[lid])}, "
                     f"{q(json.dumps(lg, ensure_ascii=False))}::jsonb) on conflict (id) do nothing;")
    lines += ["", "commit;", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({OUT.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
