"""Portal products: gazetteer, name matching, class breaks, rainfall/drought loaders, templates, exports."""
import io
import json

import numpy as np
import pandas as pd
import pytest

from agriclimate import classes, exports, reference, templates
from agriclimate.envi import config
from agriclimate.envi.io_loader import clean_name, match_name
from agriclimate.products import drought, envi_product, rainfall_dekad, rainfall_seasonal, recommend, reference_layers

SAMPLE = config.ROOT / "data" / "sample"          # synthetic rainfall/irrigation demo files
DEKAD = SAMPLE / "DEMO_rainfall_10day_2026-10-01.xlsx"   # synthetic, regenerated by scripts.make_demo_samples
SEASONAL = SAMPLE / "DEMO_rainfall_seasonal_2026-10_2027-03.xlsx"
DEKAD_SETTINGS = {"period_start": "2026-10-01", "period_end": "2026-10-10", "issue_date": "2026-09-30"}


def xlsx(df: pd.DataFrame) -> bytes:
    b = io.BytesIO()
    df.to_excel(b, index=False)
    return b.getvalue()


# ---------------------------------------------------------------- gazetteer ---

def test_gazetteer_has_77_municipalities_with_psgc():
    g = reference.gazetteer_table()
    assert len(g) == 77 and g.area_key.is_unique
    assert g.psgc.notna().all() and g.psgc.str.fullmatch(r"\d{9}").all()
    assert g.province_label.nunique() == 6
    assert set(g[g.is_city].label) == {"Baguio City", "Tabuk City"}


def test_every_gazetteer_name_matches_itself_and_its_gis_name():
    gaz = reference.gazetteer()
    for _, r in reference.gazetteer_table().iterrows():
        for raw in (r.label, r.gis_name, r.label.upper(), r.short_name):
            m = match_name(raw, r.province, "municipal", gaz)
            assert m["area_key"] == r.area_key, (raw, m)


@pytest.mark.parametrize("raw,hint,key", [
    ("Baguio City", None, "BENGUET|BAGUIO"), ("City of Baguio", "BENGUET", "BENGUET|BAGUIO"),
    ("Baguio", None, "BENGUET|BAGUIO"), ("Tabuk City", None, "KALINGA|TABUK"),
    ("City of Tabuk", "KALINGA", "KALINGA|TABUK"), ("Tabuk", None, "KALINGA|TABUK"),
    ("Peñarrubia", "ABRA", "ABRA|PENARRUBIA"), ("PE�ARRUBIA", "ABRA", "ABRA|PENARRUBIA"),
    ("Sta. Marcela", "APAYAO", "APAYAO|SANTA MARCELA"), ("Paracelis", "KALINGA", "MOUNTAIN PROVINCE|PARACELIS"),
    ("Bangued (Abra)", None, "ABRA|BANGUED"),
])
def test_known_variants(raw, hint, key):
    assert match_name(raw, hint, "municipal", reference.gazetteer())["area_key"] == key


def test_mt_province_expands():
    assert clean_name("Mt. Province") == "MOUNTAIN PROVINCE"


# ----------------------------------------------------------------- classes ---

@pytest.mark.parametrize("v,label,desc", [(0, "0–5", "No Rain"), (4.99, "0–5", "No Rain"), (5, "5–15", "Very Light Rain"),
                                          (15, "15–37.5", "Light Rain"), (37.5, "37.5–75", "Moderate Rain"),
                                          (75, "75–150", "Heavy Rain"), (150, "150–250", "Intense Rain"),
                                          (250, "250–400", "Torrential Rain"), (400, "> 400", "Extreme Rain")])
def test_dekad_classes_at_breaks(v, label, desc):
    lg = classes.preset("rainfall_dekad")
    lab, _ = classes.assign(pd.Series([v]), lg)
    assert lab.iloc[0] == label
    assert next(c["desc"] for c in lg["classes"] if c["label"] == label) == desc


@pytest.mark.parametrize("v,label", [(0, "0–50"), (50, "50–100"), (499.9, "400–500"), (500, "> 500")])
def test_monthly_classes_at_breaks(v, label):
    assert classes.assign(pd.Series([v]), classes.preset("rainfall_month"))[0].iloc[0] == label


@pytest.mark.parametrize("v,word", [(39, "Way below"), (40, "Way below"), (41, "Below"), (80, "Below"),
                                    (81, "Near"), (120, "Near"), (121, "Above")])
def test_pct_normal_classes(v, word):
    assert classes.assign(pd.Series([v]), classes.preset("pct_normal"))[0].iloc[0].startswith(word)


def test_nan_is_no_data_and_custom_breaks():
    lg = classes.preset("rainfall_dekad", {"breaks": [0, 20, 40]})
    lab, col = classes.assign(pd.Series([np.nan, 5, 20, 99]), lg)
    assert lab.tolist() == ["No data", "0–20", "20–40", "> 40"] and col.iloc[0] == classes.NO_DATA_COLOR
    with pytest.raises(ValueError):
        classes.graduated("x", "x", "mm", [0, 10, 5], ["#000"] * 3)


# ------------------------------------------------------------------ dekad ---

def test_dekad_sample_builds_one_map_per_day():
    p = rainfall_dekad.build(DEKAD.read_bytes(), DEKAD.name, DEKAD_SETTINGS)
    assert p["ok"], p["report"]["errors"]
    ids = [lyr["id"] for lyr in p["layers"]]
    assert ids == [f"d_2026-10-{d:02d}" for d in range(1, 11)] + ["total"]
    assert [lyr["label"] for lyr in p["layers"][:2]] == ["October 1", "October 2"]
    assert p["valid_text"] == "Valid from October 1 – October 10, 2026"
    lyr = p["layers"][-1]
    assert len(lyr["values"]) == 77 and lyr["unit"] == "mm"
    assert p["period"]["label"] == "October 1–10, 2026" and len(p["period"]["days"]) == 10
    assert sum(c["count"] for c in lyr["legend"]["classes"]) == 77


def test_dekad_daily_columns_summed_and_errors_point_to_cells():
    df = pd.DataFrame({"PROVINCE": ["Abra", "Abra", "Benguet"], "MUNICIPALITY": ["Bangued", "Tubo", "Baguio City"],
                       "DAY_1": [1, 2, "x"], "DAY_2": [3, -1, 5]})
    p = rainfall_dekad.build(xlsx(df), "d.xlsx", DEKAD_SETTINGS)
    errs = " | ".join(p["report"]["errors"])
    assert "row 4, column DAY_1" in errs and "'x' is not a number" in errs
    assert "row 3, column DAY_2" in errs and "negative" in errs
    df.loc[1, "DAY_2"], df.loc[2, "DAY_1"] = 4, 0
    p = rainfall_dekad.build(xlsx(df), "d.xlsx", DEKAD_SETTINGS)
    assert p["ok"]
    v = p["layers"][-1]["values"]                       # 10-day total
    assert v["ABRA|BANGUED"]["value"] == 4 and v["BENGUET|BAGUIO"]["value"] == 5
    assert p["layers"][0]["values"]["ABRA|BANGUED"]["value"] == 1 and p["layers"][1]["values"]["ABRA|BANGUED"]["value"] == 3
    assert v["IFUGAO|BANAUE"]["class"] == "No data"
    assert any("74 of 77 municipalities are missing" in w for w in p["report"]["warnings"])


def test_dekad_subtotals_skipped_and_max_warning():
    df = pd.DataFrame({"MUNICIPALITY": ["CAR", "Abra", "Bangued", "Tubo"], "RAINFALL_MM": [9999, 999, 600, 20]})
    p = rainfall_dekad.build(xlsx(df), "d.xlsx", {**DEKAD_SETTINGS, "max_warn_mm": 500})
    assert p["ok"]
    assert p["report"]["n_subtotal_rows"] == 2
    assert [w for w in p["report"]["warnings"] if "above 500" in w] == [
        "row 4, column RAINFALL_MM: 600 mm is above 500 mm – please check."]


def test_dekad_requires_dates_and_column():
    p = rainfall_dekad.build(xlsx(pd.DataFrame({"MUNICIPALITY": ["Tubo"], "X": [1]})), "d.xlsx", {})
    assert not p["ok"] and any("DAY_1" in e for e in p["report"]["errors"])


def test_unmatched_row_has_suggestions_and_manual_assignment():
    df = pd.DataFrame({"PROVINCE": ["Abra"], "MUNICIPALITY": ["Atlantis"], "RAINFALL_MM": [12]})
    p = rainfall_dekad.build(xlsx(df), "d.xlsx", DEKAD_SETTINGS)
    un = p["report"]["unmatched"]
    assert len(un) == 1 and len(un[0]["suggestions"]) == 3
    p = rainfall_dekad.build(xlsx(df), "d.xlsx", {**DEKAD_SETTINGS,
                                                  "manual_matches": {"rainfall_dekad|Atlantis": "ABRA|TUBO"}})
    assert p["layers"][-1]["values"]["ABRA|TUBO"]["value"] == 12
    assert any("no daily maps" in w for w in p["report"]["warnings"])


# --------------------------------------------------------------- seasonal ---

def test_seasonal_sample_layers():
    p = rainfall_seasonal.build(SEASONAL.read_bytes(), SEASONAL.name, {"issue_date": "2026-09-30"})
    assert p["ok"], p["report"]["errors"]
    assert [lyr["id"] for lyr in p["layers"]] == [f"m_{m}" for m in ("2026-10", "2026-11", "2026-12", "2027-01",
                                                                    "2027-02", "2027-03")] + ["season_total",
                                                                                              "pct_normal"]
    assert p["period"]["label"] == "October 2026 – March 2027"
    assert p["layers"][0]["legend"]["classes"][-1]["label"] == "> 500"


def test_seasonal_month_names_without_year_and_pct_from_normal():
    df = pd.DataFrame({"MUNICIPALITY": ["Tubo", "Pilar"], "PROVINCE": ["Abra", "Abra"], "November": [100, 50],
                       "December": [50, 20], "January": [10, 5], "NORMAL_MM": [200, 300]})
    p = rainfall_seasonal.build(xlsx(df), "s.xlsx", {"issue_date": "2026-10-15", "period_start": "2026-11"})
    assert p["ok"], p["report"]["errors"]
    assert p["period"]["months"] == ["2026-11", "2026-12", "2027-01"]
    pct = next(lyr for lyr in p["layers"] if lyr["id"] == "pct_normal")["values"]
    assert pct["ABRA|TUBO"]["value"] == 80 and pct["ABRA|TUBO"]["class"].startswith("Below")


# ---------------------------------------------------------------- drought ---

def test_drought_manual_template_one_layer_per_month():
    src = (config.DEFAULT_FILES["drought"]).read_bytes()
    p = drought.build(src, "drought forecast.csv", {"issue_date": "2026-09-15", "period_start": "2026-10"})
    assert p["ok"] and p["level"] == "provincial" and len(p["layers"]) == 6
    jan = p["layers"][3]
    assert jan["label"] == "January 2027"
    assert jan["values"]["ABRA|BANGUED"]["class"] == "Drought" and jan["values"]["ABRA|BANGUED"]["color"] == "#e5383b"
    assert p["layers"][0]["values"]["BENGUET|BAGUIO"]["class"] == "Not affected"
    assert "Abra" in recommend.drought(p)


def test_drought_rejects_unknown_category():
    p = drought.build(b"PROVINCE,October\nAbra,very dry\n", "d.csv", {"issue_date": "2026-09-15",
                                                                       "period_start": "2026-10"})
    assert not p["ok"]


# ------------------------------------------------------------------- ENVI ---

def test_envi_acceptance_numbers():
    files = {k: (p.read_bytes(), p.name) for k, p in config.DEFAULT_FILES.items()}
    equal = {"hazard": 1 / 3, "damage": 1 / 3, "crops": 1 / 3}          # acceptance criterion: equal weights
    p = envi_product.build(files, {"issue_date": "2026-09-15", "period_start": "2026-10", "period_end": "2027-03",
                                   "weights": equal})
    assert p["ok"]
    top = p["summary"]["top10"][0]
    assert top["area"] == "Tabuk City" and round(top["envi"], 3) == 0.806 and top["class"] == "Very High"
    cc = p["summary"]["class_counts"]
    assert [cc[c] for c in config.CLASS_NAMES] == [14, 44, 11, 7, 1]
    crops = envi_product.crop_table(p)
    assert crops["KALINGA|TABUK"] == {"Corn": 1336.0, "Rice": 7740.4}


# --------------------------------------------------------- reference layers ---

def test_crops_and_irrigation_layers():
    p = config.DEFAULT_FILES["crops"]
    c = reference_layers.build_crops(p.read_bytes(), p.name, {"as_of": "2026-09-15"})
    assert c["ok"] and c["crops"] == ["Corn", "Rice"] and len(c["values"]) == 77
    irr = reference_layers.build_irrigation((SAMPLE / "DEMO_irrigation_sources.xlsx").read_bytes(), "i.xlsx")
    assert irr["ok"] and len(irr["geojson"]["features"]) == 6
    bad = pd.DataFrame({"NAME": ["A", "B"], "TYPE": ["NIS", "weird"], "LAT": [120.9, 17.0], "LON": [17.0, 121.0]})
    irr = reference_layers.build_irrigation(xlsx(bad), "i.xlsx")
    assert any("swapped" in e for e in irr["report"]["errors"])
    assert any("saved as OTHER" in w for w in irr["report"]["warnings"])


# --------------------------------------------------------------- templates ---

@pytest.mark.parametrize("kind", ["rainfall_dekad", "rainfall_seasonal"])
def test_template_roundtrip(kind):
    name, data = templates.template(kind)
    df = pd.read_excel(io.BytesIO(data), sheet_name="DATA")
    assert len(df) == 77 and "README" in pd.ExcelFile(io.BytesIO(data)).sheet_names
    for c in df.columns[3:]:
        df[c] = 42.0
    if kind == "rainfall_dekad":
        p = rainfall_dekad.build(xlsx(df), name, DEKAD_SETTINGS)
    else:
        df["SEASON_TOTAL"] = 42.0 * 6
        df["PCT_NORMAL"] = 100.0
        p = rainfall_seasonal.build(xlsx(df), name, {"issue_date": "2026-09-30"})
    assert p["ok"], p["report"]["errors"][:3]
    assert p["report"]["n_unmatched"] == 0 and not p["report"]["missing_areas"]
    assert {m for m in p["report"]["methods"]} == {"exact"}


def test_drought_template_roundtrip():
    name, data = templates.template("drought")
    df = pd.read_csv(io.BytesIO(data), encoding="utf-8-sig")
    assert len(df) == 6 and list(df.columns[:2]) == ["ID", "PROVINCE"]
    for c in df.columns[2:]:
        df[c] = "dry spell"
    p = drought.build(df.to_csv(index=False).encode(), name, {"issue_date": "2026-09-15", "period_start": "2026-10"})
    assert p["ok"] and len(p["layers"]) == 6


# ----------------------------------------------------------------- exports ---

def test_exports_are_map_images_and_pdfs(tmp_path):
    p = rainfall_dekad.build(DEKAD.read_bytes(), DEKAD.name, DEKAD_SETTINGS)
    m = exports.export_product(p, tmp_path)
    assert m["labels_ok"] and len(m["maps"]) == 11                       # 10 daily maps + the 10-day total
    reps = json.loads((tmp_path / "label_report.json").read_text(encoding="utf-8"))
    assert all(r["placed"] == 83 and r["overlaps"] == [] for r in reps.values())
    from PIL import Image
    import zipfile
    mp = m["maps"][0]
    assert set(mp) == {"layer", "label", "alt", "png", "pdf", "jpg"}
    assert round(Image.open(tmp_path / mp["png"]).info["dpi"][0]) == 400
    assert (tmp_path / mp["pdf"]).read_bytes()[:4] == b"%PDF"
    assert max(Image.open(tmp_path / mp["jpg"]).size) == exports.PREVIEW_WIDTH       # sharp preview for photo mode
    assert list(m["files"]) == ["zip"]
    names = zipfile.ZipFile(tmp_path / m["files"]["zip"]).namelist()
    assert len(names) == 22 and all(n.endswith((".png", ".pdf")) for n in names)
    assert "CAR_rainfall_dekad_2026-10-01_png.png" in names


# ------------------------------------------------------- farm recommendations ---

def test_farm_recommendations_drafted_for_rice_corn_hvc():
    from agriclimate import api
    from agriclimate.products import crop_advice
    d = api.build_payload("drought", {"file": (config.DEFAULT_FILES["drought"].read_bytes(), "d.csv")},
                          {"issue_date": "2026-09-15", "period_start": "2026-10"})
    adv = crop_advice.advice_of(d)
    assert set(adv) == {"rice", "corn", "hvc"} and all(len(v) <= 260 for v in adv.values())
    assert "January 2027" in adv["rice"]                       # drought onset in the advice
    assert d["crop_advice_draft"] == adv
    # edited text wins over the draft
    e = api.build_payload("drought", {"file": (config.DEFAULT_FILES["drought"].read_bytes(), "d.csv")},
                          {"issue_date": "2026-09-15", "period_start": "2026-10",
                           "texts": {"advice_rice": "Edited rice advice."}})
    assert crop_advice.advice_of(e)["rice"] == "Edited rice advice."
    s = api.build_payload("rainfall_seasonal", {"file": (SEASONAL.read_bytes(), SEASONAL.name)},
                          {"issue_date": "2026-09-30"})
    assert set(crop_advice.advice_of(s)) == {"rice", "corn", "hvc"}
    season = next(lyr for lyr in s["layers"] if lyr["id"] == "season_total")
    assert all(c.get("desc") for c in season["legend"]["classes"])     # word descriptions, not only values


# ---------------------------------------------------- standing crops (dynamic) ---

def test_crops_upload_any_crop_columns_and_title_rows():
    from agriclimate.products.reference_layers import build_crops, crop_name
    g = reference.gazetteer_table()
    df = pd.DataFrame({"PSGC": g.psgc, "AREA": g.label, "Rice Total": 10.0, "Corn Total": 5.0, "Coffee (ha)": 2.5,
                       "Cabbage area": 3.0, "Total": 20.5})
    buf = io.BytesIO()
    with pd.ExcelWriter(buf) as xw:
        pd.DataFrame([["STANDING CROPS AS OF OCT 1, 2026"]]).to_excel(xw, index=False, header=False)
        df.to_excel(xw, index=False, startrow=2)
    r = build_crops(buf.getvalue(), "crops.xlsx", {"as_of": "2026-10-01"})
    assert r["ok"], r["report"]["errors"]
    assert r["crops"] == ["Rice", "Corn", "Coffee", "Cabbage"]                 # "Total" is not a crop
    assert len(set(r["colors"].values())) == 4 and r["colors"]["Rice"] == "#2e7d32"
    assert r["values"]["KALINGA|TABUK"] == {"Rice": 10.0, "Corn": 5.0, "Coffee": 2.5, "Cabbage": 3.0}
    assert crop_name("Sweet Potato (ha)") == "Sweet Potato" and crop_name("Total") == ""


def test_seasonal_map_with_crop_circles(tmp_path):
    from agriclimate import render
    from agriclimate.products.reference_layers import build_crops
    c = build_crops(config.DEFAULT_FILES["crops"].read_bytes(), config.DEFAULT_FILES["crops"].name, {"as_of": "2026-09-15"})
    p = rainfall_seasonal.build(SEASONAL.read_bytes(), SEASONAL.name, {"issue_date": "2026-09-30"})
    p["crop_overlay"] = {"as_of": c["as_of"], "crops": c["colors"], "values": c["values"]}
    r = render.render_layer(p, p["layers"][0], tmp_path, "m")
    assert r["label_report"]["ok"] and r["label_report"]["placed"] == 83


def test_envi_default_weights_50_25_25():
    files = {k: (p.read_bytes(), p.name) for k, p in config.DEFAULT_FILES.items()}
    p = envi_product.build(files, {"issue_date": "2026-09-15", "period_start": "2026-10", "period_end": "2027-03"})
    assert p["method"]["weights"] == {"hazard": 0.5, "damage": 0.25, "crops": 0.25}
    v = p["layers"][0]["values"]["KALINGA|TABUK"]
    # normalized values are rounded to 2 decimals in the payload, hence the tolerance
    assert v["envi"] == pytest.approx(0.5 * v["hazard_norm"] + 0.25 * v["damage_norm"] + 0.25 * v["crops_norm"], abs=0.01)


def test_envi_exports_with_crop_circles(tmp_path):
    from PIL import Image
    from agriclimate.products.reference_layers import build_crops
    files = {k: (p.read_bytes(), p.name) for k, p in config.DEFAULT_FILES.items()}
    s = {"issue_date": "2026-09-15", "period_start": "2026-10", "period_end": "2027-03"}
    p = envi_product.build(files, s)
    c = build_crops(config.DEFAULT_FILES["crops"].read_bytes(), config.DEFAULT_FILES["crops"].name, {"as_of": "2026-09-15"})
    ov = {"as_of": c["as_of"], "crops": {"Rice": c["colors"]["Rice"]}, "values": c["values"]}
    m = exports.export_product(p, tmp_path, {**s, "crop_overlay": ov}, files)
    mp = m["maps"][0]
    assert m["labels_ok"]
    assert Image.open(tmp_path / mp["presentation"]).size == (5760, 3240)          # high-definition presentation
    assert Image.open(tmp_path / mp["poster"]).size == (3720, 5262)                # A4 at 450 dpi
    for k in ("presentation_pdf", "poster_pdf", "pdf"):
        assert (tmp_path / mp[k]).read_bytes()[:4] == b"%PDF"
    assert {"presentation_web", "poster_web"} <= set(mp)
